<?php
declare(strict_types=1);
namespace BSP\Gamification\Admin;

final class CollectiblesAdminPage
{
    public static function register(): void
    {
        add_action('admin_menu',array(__CLASS__,'menu')); add_action('admin_post_bsp_collectible_save',array(__CLASS__,'save')); add_action('admin_post_bsp_collectibles_seed_bosch',array(__CLASS__,'seedBosch')); add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));
    }
    public static function menu(): void { add_submenu_page('woocommerce',__('Collectibles','sbdp'),__('Collectibles','sbdp'),'manage_woocommerce','bsp-collectibles',array(__CLASS__,'render')); }
    public static function assets(string $hook): void { if($hook!=='woocommerce_page_bsp-collectibles')return; wp_enqueue_media(); wp_enqueue_script('bsp-collectibles-admin',SBDP_URL.'modules/gamification/assets/collectibles-admin.js',array(),defined('SBDP_VER')?SBDP_VER:'1',true); }
    public static function render(): void
    {
        if(!current_user_can('manage_woocommerce'))return; global $wpdb; $editId=(int)($_GET['edit']??0); $item=$editId?$wpdb->get_row($wpdb->prepare("SELECT c.*,r.route_id,r.checkpoint_id,r.unlock_event,r.display_order FROM {$wpdb->prefix}bsp_collectibles c LEFT JOIN {$wpdb->prefix}bsp_collectible_routes r ON r.collectible_id=c.id WHERE c.id=%d LIMIT 1",$editId),ARRAY_A):array(); $items=$wpdb->get_results("SELECT c.*,COUNT(r.id) route_count,COUNT(u.id) unlock_count FROM {$wpdb->prefix}bsp_collectibles c LEFT JOIN {$wpdb->prefix}bsp_collectible_routes r ON r.collectible_id=c.id LEFT JOIN {$wpdb->prefix}bsp_user_collectibles u ON u.collectible_id=c.id GROUP BY c.id ORDER BY c.updated_at DESC",ARRAY_A);
        echo '<div class="wrap"><h1>'.esc_html__('Collectibles','sbdp').'</h1><p>'.esc_html__('Verzamelobjecten gebruiken bestaande route- en checkpoint-ID’s. Een unlock ontstaat uitsluitend uit een geverifieerd server-event.','sbdp').'</p><h2>'.($editId?esc_html__('Collectible bewerken','sbdp'):esc_html__('Collectible toevoegen','sbdp')).'</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bsp_collectible_save');echo '<input type="hidden" name="action" value="bsp_collectible_save"><input type="hidden" name="id" value="'.$editId.'"><table class="form-table">';
        self::input('title','Titel',$item,true);self::input('slug','Slug',$item,true);self::select('type','Type',array('person'=>'Persoon','building'=>'Gebouw','artwork'=>'Kunstwerk','symbol'=>'Symbool','object'=>'Voorwerp','animal'=>'Dier'),$item);self::select('rarity','Rarity',array('common'=>'Common','uncommon'=>'Uncommon','rare'=>'Rare','epic'=>'Epic','legendary'=>'Legendary'),$item);self::textarea('short_description','Korte beschrijving',$item);self::textarea('story_content','Verhaal',$item);self::media('image_attachment_id','Afbeelding',$item);self::media('silhouette_attachment_id','Silhouette',$item);self::input('route_id','Route ID',$item,true,'number');self::input('checkpoint_id','Checkpoint ID',$item);self::select('unlock_event','Unlock-event',array('qr.checkpoint_verified'=>'QR/checkpoint geverifieerd','route.completed'=>'Route voltooid','audio_tour.completed'=>'Audiotour voltooid'),$item);self::select('hint_mode','Hint',array('hidden'=>'Verborgen','global'=>'Globale hint','exact'=>'Exacte hint'),$item);self::textarea('hint_text','Hinttekst',$item);self::input('xp_reward','XP-beloning',$item,false,'number');self::select('status','Status',array('draft'=>'Concept','active'=>'Actief','seasonal'=>'Seizoen','archived'=>'Gearchiveerd'),$item);echo '</table>';submit_button(__('Collectible opslaan','sbdp'));echo '</form><h2>'.esc_html__('Collectie','sbdp').'</h2><table class="widefat striped"><thead><tr><th>Object</th><th>Type</th><th>Rarity</th><th>Routes</th><th>Unlocks</th><th>Status</th></tr></thead><tbody>';foreach((array)$items as $row){echo '<tr><td><a href="'.esc_url(admin_url('admin.php?page=bsp-collectibles&edit='.(int)$row['id'])).'"><strong>'.esc_html($row['title']).'</strong></a><br><code>'.esc_html($row['slug']).'</code></td><td>'.esc_html($row['type']).'</td><td>'.esc_html($row['rarity']).'</td><td>'.(int)$row['route_count'].'</td><td>'.(int)$row['unlock_count'].'</td><td>'.esc_html($row['status']).'</td></tr>';}echo '</tbody></table></div>';
    }
    public static function save(): void
    {
        if(!current_user_can('manage_woocommerce'))wp_die('Forbidden',403);check_admin_referer('bsp_collectible_save');global $wpdb;$id=(int)($_POST['id']??0);$allowedTypes=array('person','building','artwork','symbol','object','animal');$allowedRarity=array('common','uncommon','rare','epic','legendary');$data=array('slug'=>sanitize_title((string)($_POST['slug']??'')),'type'=>in_array($_POST['type']??'',$allowedTypes,true)?$_POST['type']:'object','title'=>sanitize_text_field((string)($_POST['title']??'')),'short_description'=>sanitize_textarea_field((string)($_POST['short_description']??'')),'story_content'=>wp_kses_post((string)($_POST['story_content']??'')),'rarity'=>in_array($_POST['rarity']??'',$allowedRarity,true)?$_POST['rarity']:'common','image_attachment_id'=>(int)($_POST['image_attachment_id']??0),'silhouette_attachment_id'=>(int)($_POST['silhouette_attachment_id']??0),'xp_reward'=>max(0,(int)($_POST['xp_reward']??15)),'hint_mode'=>in_array($_POST['hint_mode']??'',array('hidden','global','exact'),true)?$_POST['hint_mode']:'hidden','hint_text'=>sanitize_textarea_field((string)($_POST['hint_text']??'')),'status'=>in_array($_POST['status']??'',array('draft','active','seasonal','archived'),true)?$_POST['status']:'draft','updated_at'=>gmdate('Y-m-d H:i:s'));if($data['slug']===''||$data['title']==='')wp_die('Titel en slug zijn verplicht.',400);if($id){$wpdb->update($wpdb->prefix.'bsp_collectibles',$data,array('id'=>$id));}else{$data['created_at']=gmdate('Y-m-d H:i:s');$wpdb->insert($wpdb->prefix.'bsp_collectibles',$data);$id=(int)$wpdb->insert_id;}$routeId=(int)($_POST['route_id']??0);$event=sanitize_text_field((string)($_POST['unlock_event']??''));if(!in_array($event,array('qr.checkpoint_verified','route.completed','audio_tour.completed','tour.step_completed'),true))$event='qr.checkpoint_verified';$wpdb->delete($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$id),array('%d'));if($routeId>0){$wpdb->insert($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$id,'route_id'=>$routeId,'checkpoint_id'=>sanitize_text_field((string)($_POST['checkpoint_id']??'')),'unlock_event'=>$event,'display_order'=>0,'is_required'=>0));}wp_safe_redirect(admin_url('admin.php?page=bsp-collectibles&saved=1'));exit;
    }
    public static function seedBosch(): void {if(!current_user_can('manage_woocommerce'))wp_die('Forbidden',403);check_admin_referer('bsp_collectibles_seed_bosch');$count=\BSP\Gamification\Support\BoschCollectibleSeeder::seed(5);wp_safe_redirect(admin_url('admin.php?page=bsp-collectibles&seeded='.$count));exit;}
    private static function input(string $name,string $label,array $item,bool $required=false,string $type='text'): void {echo '<tr><th><label for="'.$name.'">'.esc_html($label).'</label></th><td><input class="regular-text" id="'.$name.'" name="'.$name.'" type="'.$type.'" value="'.esc_attr((string)($item[$name]??'')).'" '.($required?'required':'').'></td></tr>';}
    private static function textarea(string $name,string $label,array $item): void {echo '<tr><th><label for="'.$name.'">'.esc_html($label).'</label></th><td><textarea class="large-text" rows="3" id="'.$name.'" name="'.$name.'">'.esc_textarea((string)($item[$name]??'')).'</textarea></td></tr>';}
    private static function select(string $name,string $label,array $options,array $item): void {if($name==='unlock_event')$options['tour.step_completed']=__('Tourhoofdstuk voltooid','sbdp');echo '<tr><th><label for="'.$name.'">'.esc_html($label).'</label></th><td><select id="'.$name.'" name="'.$name.'">';foreach($options as $value=>$text)echo '<option value="'.esc_attr($value).'" '.selected($item[$name]??'',$value,false).'>'.esc_html($text).'</option>';echo '</select></td></tr>';}
    private static function media(string $name,string $label,array $item): void {echo '<tr><th>'.esc_html($label).'</th><td><input class="bsp-media-id" id="'.$name.'" name="'.$name.'" type="number" value="'.(int)($item[$name]??0).'"><button class="button bsp-select-media" type="button" data-target="'.$name.'">'.esc_html__('Kies afbeelding','sbdp').'</button></td></tr>';}
}
