<?php
declare(strict_types=1);
namespace BSP\Gamification\Support;

final class BoschCollectibleSeeder
{
    public static function seed(int $tourId=5): int
    {
        if(get_post_type($tourId)!=='sbdp_private_tour')return 0;global $wpdb;$steps=get_posts(array('post_type'=>'sbdp_tour_step','post_status'=>'publish','post_parent'=>$tourId,'numberposts'=>-1,'orderby'=>'menu_order','order'=>'ASC'));$rarities=array('common','common','common','common','common','common','common','common','uncommon','uncommon','uncommon','uncommon','uncommon','rare','rare','rare','epic','epic','rare','legendary');$types=array('symbol','building','person','artwork','building','building','symbol','object','artwork','building','person','object','symbol','person','building','symbol','animal','object','symbol','artwork');$ids=array();$fallbackImage=(int)get_post_thumbnail_id($tourId);$sealId=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}bsp_collectibles WHERE slug=%s",'het-zegel-van-bosch'));
        foreach($steps as $index=>$step){$slug='jheronimus-bosch-'.sanitize_title($step->post_name?:$step->post_title);$existing=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}bsp_collectibles WHERE slug=%s",$slug));if($index===0&&$sealId>0){if($existing){$wpdb->update($wpdb->prefix.'bsp_collectibles',array('status'=>'archived','updated_at'=>gmdate('Y-m-d H:i:s')),array('id'=>$existing));$wpdb->delete($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$existing),array('%d'));}$wpdb->update($wpdb->prefix.'bsp_collectibles',array('type'=>'symbol','rarity'=>'legendary','status'=>'active','hint_mode'=>'global','hint_text'=>'Ontgrendel dit symbool door hoofdstuk 1 te voltooien.','updated_at'=>gmdate('Y-m-d H:i:s')),array('id'=>$sealId));$wpdb->delete($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$sealId),array('%d'));$wpdb->insert($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$sealId,'route_id'=>$tourId,'checkpoint_id'=>(string)$step->ID,'unlock_event'=>'tour.step_completed','display_order'=>0,'is_required'=>1));$ids[]=$sealId;continue;}$content=trim(wp_strip_all_tags((string)$step->post_content));$short=wp_trim_words($content?:sprintf('Ontdek het verhaal achter %s tijdens de Jeroen Bosch Tour.',$step->post_title),24);$image=(int)get_post_thumbnail_id($step->ID);if(!$image){$url=(string)get_post_meta($step->ID,'_sbdp_step_image_url',true);$image=$url&&function_exists('attachment_url_to_postid')?(int)attachment_url_to_postid($url):0;}$data=array('slug'=>$slug,'type'=>$types[$index]??'symbol','title'=>$step->post_title,'short_description'=>$short,'story_content'=>$content,'rarity'=>$rarities[$index]??'common','image_attachment_id'=>$image?:$fallbackImage,'silhouette_attachment_id'=>$fallbackImage,'xp_reward'=>($rarities[$index]??'common')==='legendary'?30:15,'hint_mode'=>'global','hint_text'=>sprintf('Te vinden bij hoofdstuk %d van de Jeroen Bosch Tour.',$index+1),'status'=>'active','updated_at'=>gmdate('Y-m-d H:i:s'));if($existing){$wpdb->update($wpdb->prefix.'bsp_collectibles',$data,array('id'=>$existing));$id=$existing;}else{$data['created_at']=gmdate('Y-m-d H:i:s');$wpdb->insert($wpdb->prefix.'bsp_collectibles',$data);$id=(int)$wpdb->insert_id;}$wpdb->delete($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$id,'route_id'=>$tourId),array('%d','%d'));$wpdb->insert($wpdb->prefix.'bsp_collectible_routes',array('collectible_id'=>$id,'route_id'=>$tourId,'checkpoint_id'=>(string)$step->ID,'unlock_event'=>'tour.step_completed','display_order'=>$index,'is_required'=>1));$ids[]=$id;}
        $set=array('slug'=>'wereld-van-jheronimus-bosch','title'=>'De wereld van Jheronimus Bosch','description'=>'Verzamel de verborgen verhalen uit alle hoofdstukken van de Jeroen Bosch Tour.','image_attachment_id'=>$fallbackImage,'xp_reward'=>200,'status'=>'active','item_ids_json'=>wp_json_encode($ids),'updated_at'=>gmdate('Y-m-d H:i:s'));$setId=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}bsp_collectible_sets WHERE slug=%s",$set['slug']));if($setId)$wpdb->update($wpdb->prefix.'bsp_collectible_sets',$set,array('id'=>$setId));else{$set['created_at']=gmdate('Y-m-d H:i:s');$wpdb->insert($wpdb->prefix.'bsp_collectible_sets',$set);}return count($ids);
    }
}
