name: PHPStan

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-php-8.1-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse --configuration=phpstan.neon.dist